import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNav from './ui/MainNav'
import Footer from './ui/Footer'
import BottmBanner from './ui/BottmBanner'

export const metadata: Metadata = {
  title: 'Roooby',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='overflow-x-hidden'>
        <MainNav />
          {children}
        <BottmBanner />
        <Footer />
      </body>
    </html>
  )
}
