import type { Metadata } from 'next'
import './globals.css'
import MainNav from './ui/MainNav'
import Footer from './ui/Footer'
import BottmBanner from './ui/BottmBanner'
import { Toaster } from 'react-hot-toast'
import { FilterContextProvider } from './contexts/FilterContext'

export const metadata: Metadata = {
  title: 'Roooby',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='overflow-x-hidden'>
        <FilterContextProvider>
          <MainNav />
          {children}
          
          <Footer />
          <Toaster />
        </FilterContextProvider>
      </body>
    </html>
  )
}
